### ISSUE TITLE
Publish

### ISSUE THREAD

**Issue by lunaryorn** [lunaryorn/play-json-refined#1]
No idea how and where. Eh, help?! :blush: @muuki88 @fthomas

**Comment by fthomas** [comment]
This guide seems up-to-date: http://www.loftinspace.com.au/blog/publishing-scala-libraries-to-sonatype.html#stage_release

**Comment by lunaryorn** [comment]
So, I made it to [Bintray](https://bintray.com/lunaryorn/maven/play-json-refined/view).  I've asked for JCenter integration; and apparently you can setup Maven Central sync afterwards.

**Comment by lunaryorn** [comment]
I've created an issue for this project: https://issues.sonatype.org/browse/OSSRH-22507

**Comment by lunaryorn** [comment]
I've got a reply and have been able to sync from Bintray to Maven Central.  I'm not sure what happens next, let's see :blush:

**Comment by fthomas** [comment]
It is on Maven Central now: http://search.maven.org/#artifactdetails|com.lunaryorn|play-json-refined_2.11|0.1|jar \o/ :tada:

**Comment by lunaryorn** [comment]
Yeah 😄

**Comment by lunaryorn** [comment]
@fthomas @muuki88 Thanks for your help, folks!
